-- FitSo Database Schema (Oracle 12c+ Compatible)
-- Clean up existing tables if re-running
BEGIN
   FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
      'USER_ITEMS', 'ITEMS', 'USER_MISSIONS', 'MISSIONS', 'GOALS',
      'BODY_MEASUREMENTS', 'WORKOUTS', 'WORKOUT_TYPES', 'PLAYER_STATE', 'USERS'
   )) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- 1. USERS
CREATE TABLE users (
  user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username       VARCHAR2(30)  NOT NULL UNIQUE,
  email          VARCHAR2(100) NOT NULL UNIQUE,
  password_hash  VARCHAR2(128) NOT NULL,
  salt           VARCHAR2(32)  NOT NULL,
  full_name      VARCHAR2(60)  NOT NULL,
  gender         VARCHAR2(10)  CHECK (gender IN ('MALE','FEMALE','OTHER')),
  birth_date     DATE,
  height_cm      NUMBER(5,1)   CHECK (height_cm BETWEEN 50 AND 250),
  created_on     DATE DEFAULT SYSDATE NOT NULL
);

-- 2. PLAYER_STATE (1:1 with USERS)
CREATE TABLE player_state (
  user_id        NUMBER PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
  total_energy   NUMBER(7) DEFAULT 0 NOT NULL CHECK (total_energy >= 0),
  coins          NUMBER(7) DEFAULT 0 NOT NULL CHECK (coins >= 0),
  pet_name       VARCHAR2(20) DEFAULT 'Buddy' NOT NULL
);

-- 3. WORKOUT_TYPES
CREATE TABLE workout_types (
  type_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name      VARCHAR2(40) NOT NULL UNIQUE,
  met_value      NUMBER(4,1)  NOT NULL CHECK (met_value > 0)
);

-- 4. WORKOUTS
CREATE TABLE workouts (
  workout_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  type_id         NUMBER NOT NULL REFERENCES workout_types(type_id),
  workout_date    DATE   NOT NULL,
  duration_min    NUMBER(4) NOT NULL CHECK (duration_min BETWEEN 1 AND 600),
  intensity       VARCHAR2(6) NOT NULL CHECK (intensity IN ('LOW','MEDIUM','HIGH')),
  calories_burned NUMBER(6) NOT NULL CHECK (calories_burned >= 0),
  energy_earned   NUMBER(4) DEFAULT 0 NOT NULL,
  coins_earned    NUMBER(4) DEFAULT 0 NOT NULL,
  notes           VARCHAR2(200)
);
CREATE INDEX ix_workouts_user_date ON workouts(user_id, workout_date);

-- 5. BODY_MEASUREMENTS
CREATE TABLE body_measurements (
  measurement_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  measured_on    DATE   NOT NULL,
  weight_kg      NUMBER(5,2) NOT NULL CHECK (weight_kg BETWEEN 20 AND 400),
  waist_cm       NUMBER(5,1) CHECK (waist_cm > 0),
  chest_cm       NUMBER(5,1) CHECK (chest_cm > 0),
  hips_cm        NUMBER(5,1) CHECK (hips_cm > 0),
  CONSTRAINT uq_meas_user_day UNIQUE (user_id, measured_on)
);

-- 6. GOALS
CREATE TABLE goals (
  goal_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  goal_type        VARCHAR2(15) NOT NULL CHECK (goal_type IN ('LOSE_WEIGHT','GAIN_MUSCLE','STAY_FIT')),
  target_weight_kg NUMBER(5,2),
  weekly_workouts  NUMBER(2) NOT NULL CHECK (weekly_workouts BETWEEN 1 AND 14),
  start_date       DATE DEFAULT SYSDATE NOT NULL,
  is_active        CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y','N'))
);

-- 7. MISSIONS
CREATE TABLE missions (
  mission_id     NUMBER PRIMARY KEY,
  title          VARCHAR2(60) NOT NULL UNIQUE,
  metric_type    VARCHAR2(20) NOT NULL CHECK (metric_type IN
     ('WORKOUT_COUNT','SINGLE_MINUTES','STREAK_DAYS','TOTAL_ENERGY','TOTAL_CALORIES','MEASUREMENT_COUNT')),
  target_value   NUMBER(6) NOT NULL CHECK (target_value > 0),
  reward_energy  NUMBER(4) DEFAULT 20 NOT NULL,
  reward_coins   NUMBER(4) DEFAULT 50 NOT NULL
);

-- 8. USER_MISSIONS
CREATE TABLE user_missions (
  user_id        NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  mission_id     NUMBER NOT NULL REFERENCES missions(mission_id),
  completed_on   DATE DEFAULT SYSDATE NOT NULL,
  PRIMARY KEY (user_id, mission_id)
);

-- 9. ITEMS
CREATE TABLE items (
  item_id        NUMBER PRIMARY KEY,
  item_name      VARCHAR2(40) NOT NULL UNIQUE,
  slot           VARCHAR2(12) NOT NULL CHECK (slot IN ('CAP','SHOES','PET_ACC','ROOM','OUTFIT')),
  price_coins    NUMBER(5) NOT NULL CHECK (price_coins > 0),
  image_file     VARCHAR2(60) NOT NULL
);

-- 10. USER_ITEMS
CREATE TABLE user_items (
  user_id        NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  item_id        NUMBER NOT NULL REFERENCES items(item_id),
  purchased_on   DATE DEFAULT SYSDATE NOT NULL,
  is_equipped    CHAR(1) DEFAULT 'N' NOT NULL CHECK (is_equipped IN ('Y','N')),
  PRIMARY KEY (user_id, item_id)
);
